version: '3.8'

services:
  php:
    image: php:latest
    volumes:
      - ./your-php-code:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql-data:
    driver: local
